# Generated by Django 5.2.5 on 2025-08-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Supports basic HTML for emphasis.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('sfx_enter', models.CharField(blank=True, help_text="Relative path under static/story/sfx, e.g. 'door_creak.mp3'", max_length=200)),
                ('tab_title', models.CharField(blank=True, max_length=60)),
                ('set_flags_on_enter', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('require_flags', models.CharField(blank=True, max_length=250)),
                ('set_flags', models.CharField(blank=True, max_length=250)),
                ('sfx_on_choose', models.CharField(blank=True, max_length=200)),
                ('next_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_choices', to='story.room')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='story.room')),
            ],
        ),
    ]
