# Generated by Django 5.2.5 on 2025-08-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='sfx_enter',
            field=models.FileField(blank=True, help_text='Upload a short sound effect (mp3, wav, ogg)', null=True, upload_to='sfx/rooms/'),
        ),
    ]
